create procedure sp_becadosAleph @clectivo varchar(4),@sesion varchar(1),@clase varchar(6)
as
begin
--COMENCEMOS n.n

SELECT 
distinct DOC.NATIONAL_ID AS ID,
PER.EMPLID AS COD_BAR,
(NOM.LAST_NAME + ' ' + NOM.SECOND_LAST_NAME + ' ' + NOM.FIRST_NAME) AS NOMBRE,
PER.SEX AS GENERO,
CONVERT(CHAR(10),PER.BIRTHDATE,112) AS FNAC,
'' as LUGAR,
PH.PHONE AS TELEFONO,
PH.PHONE AS CELULAR, --lo mismo que telefono
(DIR.ADDRESS1 + ', ' + DIST.DESCR + ', ' + PROV.DESCR + ', ' + ST.DESCR) AS DIRECCION,
EM.EMAIL_ADDR AS EMAIL,
(case CLA.ACAD_CAREER
when 'EXIN' then CONVERT(CHAR(10),DATEADD(YEAR,+1, [CLA].END_DT),112)
else CONVERT(CHAR(10),DATEADD(DAY,-2, [CLA].END_DT),112) end) AS F_FINAL,
--CONVERT(CHAR(10),(CLA.END_DT),112) AS F_ULTIMO_CURSO,
--GETDATE() AS FECHA_REGISTRO,
(case CLA.ACAD_CAREER
when 'EXIN' then '07'
else '09' end) as ESTATUS,
'' as TIPO,
'ACP50,BBRIT,BBCAB' AS SUB_BIB,
CLA.ACAD_CAREER AS NOTA_1, 
LTRIM(RTRIM([CLA].CATALOG_NBR)) AS NOTA_2,      
[SES].LOCATION AS NOTA_3,
'' as LOCAL_LIB,
'' as PIP_LIB,
'' as PIB_TOTAL,
'' as PIB_ACTIVA,
'' as TIT_LIMITE  
FROM
PS_PERSONAL_DATA PER
LEFT OUTER JOIN PS_PERS_NID DOC
ON DOC.EMPLID = PER.EMPLID
LEFT OUTER JOIN PS_NAMES NOM
ON NOM.EMPLID = PER.EMPLID
LEFT OUTER JOIN PS_ADDRESSES DIR
ON DIR.EMPLID = PER.EMPLID
LEFT OUTER JOIN PS_STATE_TBL [ST]
ON [ST].STATE = [DIR].STATE
LEFT OUTER JOIN PS_MBO_PROVINC_TBL [PROV]
ON PROV.MBO_PROVINCIA = DIR.CITY AND PROV.STATE = DIR.STATE
LEFT OUTER JOIN PS_MBO_DISTRIT_TBL [DIST]
ON DIST.MBO_DISTRITO = DIR.COUNTY AND DIST.MBO_PROVINCIA = DIR.CITY AND DIST.STATE = DIR.STATE
LEFT OUTER JOIN PS_PERSONAL_PHONE PH
ON PH.EMPLID = PER.EMPLID
AND PH.PREF_PHONE_FLAG='Y'
LEFT OUTER JOIN PS_EMAIL_ADDRESSES EM
ON EM.EMPLID = PER.EMPLID
AND EM.PREF_EMAIL_FLAG='Y'
LEFT OUTER JOIN PS_STDNT_ENRL INS
ON INS.EMPLID = PER.EMPLID,

(PS_CLASS_TBL [CLA]
       LEFT OUTER JOIN PS_CLASS_MTG_PAT [MOD]
             ON [MOD].CRSE_ID = [CLA].CRSE_ID
             AND [MOD].CRSE_OFFER_NBR = [CLA].CRSE_OFFER_NBR
             AND [MOD].STRM = [CLA].STRM
             AND [MOD].SESSION_CODE = [CLA].SESSION_CODE
             AND [MOD].CLASS_SECTION = [CLA].CLASS_SECTION
             AND [MOD].CLASS_MTG_NBR = 1),
       PS_LVF_TERM_TBL3 [SES],
       PSXLATITEM [FRE]
WHERE 
 [CLA].STRM = [INS].STRM
       AND [CLA].INSTITUTION = [INS].INSTITUTION
       AND [CLA].ACAD_CAREER = [INS].CRSE_CAREER
       AND [CLA].CLASS_NBR = [INS].CLASS_NBR
       AND [SES].INSTITUTION = [CLA].INSTITUTION
       AND [SES].ACAD_CAREER = [CLA].ACAD_CAREER
       AND [SES].STRM = [CLA].STRM
       AND [SES].SESSION_CODE = [CLA].SESSION_CODE
       AND [FRE].FIELDNAME = 'LVF_TURNO_IDT'
       AND [FRE].FIELDVALUE = [SES].LVF_TURNO_IDT
       AND [FRE].EFFDT = (
							SELECT MAX([FREM].EFFDT) FROM PSXLATITEM [FREM]
							WHERE
							[FREM].FIELDNAME = [FRE].FIELDNAME AND [FREM].FIELDVALUE = [FRE].FIELDVALUE AND [FREM].EFFDT <= GETDATE()
							)
        AND [INS].STDNT_ENRL_STATUS='E'         
        AND [INS].STRM =@clectivo --CICLO LECTIVO QUE CURSA EL ALUMNO *
        AND DOC.PRIMARY_NID='Y' AND
         DIR.EFF_STATUS='A' AND ST.COUNTRY='PER'
         AND CLA.SESSION_CODE LIKE (@sesion+'%') --PARA MANEJAR LAS SESIONES LA LETRA RESPECTIVA A CADA MES ( L - DICIEMBRE) *
         AND CLA.ACAD_CAREER IN ('EXIN') -- CORRESPONDE A GRADO ACADEMICO *
         AND LTRIM([CLA].CATALOG_NBR ) like ISNULL(@clase,'%') -- CORRESPONDE A LA CLASE *
        --ORDER BY [CLA].SESSION_CODE ASC
		
		/*GROUP BY
		DOC.NATIONAL_ID,PER.EMPLID,(NOM.LAST_NAME + ' ' + NOM.SECOND_LAST_NAME + ' ' + NOM.FIRST_NAME),PER.SEX,CONVERT(CHAR(10),PER.BIRTHDATE,112)
		,PH.PHONE,PH.PHONE,(DIR.ADDRESS1 + ', ' + DIST.DESCR + ', ' + PROV.DESCR + ', ' + ST.DESCR),
		EM.EMAIL_ADDR,CLA.ACAD_CAREER,LTRIM(RTRIM([CLA].CATALOG_NBR)) ,[SES].LOCATION		*/
		ORDER BY COD_BAR ASC
end

exec sp_becadosAleph '2015','C',null




