	/*	

		INSERT INTO [dbo].[BR_USUARIOS_ALEPH_HIS] 
		SELECT A.*
		FROM [dbo].[BR_USUARIOS_ALEPH_TST] A --x
		INNER JOIN [dbo].[BR_USUARIOS_ALEH_RSET] B ON A.COD_BAR=B.COD_BAR AND
		( A.ID<>B.ID OR A.NOMBRE<>B.NOMBRE OR A.GENERO<>B.GENERO OR A.FNAC<>B.FNAC
		OR A.LUGAR<>B.LUGAR OR A.TELEFONO<>B.TELEFONO OR A.CELULAR<>B.CELULAR
		OR A.DIRECCION<>B.DIRECCION OR A.EMAIL<>B.EMAIL OR A.F_FINAL<>B.F_FINAL
		OR A.ESTATUS<>B.ESTATUS OR A.TIPO<>B.TIPO OR A.SUB_BIB<>B.SUB_BIB
		OR A.NOTA_1<>B.NOTA_1 OR A.NOTA_2<>B.NOTA_2 OR A.NOTA_3<>B.NOTA_3
		OR A.LOCAL_LIB<>B.LOCAL_LIB OR A.PIP_LIB<>B.PIP_LIB OR A.PIB_TOTAL<>B.PIB_TOTAL
		OR A.PIB_ACTIVA<>B.PIB_ACTIVA OR A.TIT_LIMITE<>B.TIT_LIMITE )

		
		--ELIMINANDO LO QUE SE ACTUALIZÓ
		/*
		DELETE A FROM #BR_ALEPH_TST A	INNER JOIN #BR_ALEPH B ON A.COD_BAR=B.COD_BAR AND
		( A.ID<>B.ID OR A.NOMBRE<>B.NOMBRE OR A.GENERO<>B.GENERO OR A.FNAC<>B.FNAC
		OR A.LUGAR<>B.LUGAR OR A.TELEFONO<>B.TELEFONO OR A.CELULAR<>B.CELULAR
		OR A.DIRECCION<>B.DIRECCION OR A.EMAIL<>B.EMAIL OR A.F_FINAL<>B.F_FINAL
		OR A.ESTATUS<>B.ESTATUS OR A.TIPO<>B.TIPO OR A.SUB_BIB<>B.SUB_BIB
		OR A.NOTA_1<>B.NOTA_1 OR A.NOTA_2<>B.NOTA_2 OR A.NOTA_3<>B.NOTA_3
		OR A.LOCAL_LIB<>B.LOCAL_LIB OR A.PIP_LIB<>B.PIP_LIB OR A.PIB_TOTAL<>B.PIB_TOTAL
		OR A.PIB_ACTIVA<>B.PIB_ACTIVA OR A.TIT_LIMITE<>B.TIT_LIMITE ) */
		DELETE A FROM [dbo].[BR_USUARIOS_ALEPH_TST] A
		 INNER JOIN [dbo].[BR_USUARIOS_ALEH_RSET] B ON A.COD_BAR=B.COD_BAR


		--ACTUALIZANDO LO QUE YA PASÓ
		UPDATE [dbo].[BR_USUARIOS_ALEPH_TST]
		SET F_FINAL='19900101'

		
		--CREAR UNA TABLA ADICIONAL
		
		--INSERCIÓN DE LA DATA ACTUALIZADA
		INSERT INTO [dbo].[BR_USUARIOS_ALEPH_TST]
		SELECT * FROM [dbo].[BR_USUARIOS_ALEH_RSET] A


		*/