//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3620
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Britanico.SacNet.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTSRV09\\SQLSRV2005DEV;Initial Catalog=BRITANICO_SACNET;User ID=sa")]
        public string BRITANICO_SACNETConnectionString {
            get {
                return ((string)(this["BRITANICO_SACNETConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTSRV09\\SQLSRV2005DEV;Initial Catalog=BRITANICO_SACNET;User ID=sa")]
        public string BRITANICO_SACNETConnectionString1 {
            get {
                return ((string)(this["BRITANICO_SACNETConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTSRV09\\SQLSRV2005DEV;Initial Catalog=BRITANICO_SACNET;User ID=sa")]
        public string BRITANICO_SACNETConnectionString2 {
            get {
                return ((string)(this["BRITANICO_SACNETConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTSRV09\\SQLSRV2005DEV;Initial Catalog=BRITANICO_SACNET;User ID=sa")]
        public string BRITANICO_SACNETConnectionString3 {
            get {
                return ((string)(this["BRITANICO_SACNETConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTSRV09\\SQLSRV2005DEV;Initial Catalog=BRITANICO_SACNET;User ID=sa")]
        public string BRITANICO_SACNETConnectionString4 {
            get {
                return ((string)(this["BRITANICO_SACNETConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTSRV09\\SQLSRV2005DEV;Initial Catalog=BRITANICO_SACNET;User ID=sa")]
        public string BRITANICO_SACNETConnectionString5 {
            get {
                return ((string)(this["BRITANICO_SACNETConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTSRV09\\SQLSRV2005DEV;Initial Catalog=BRITANICO_SACNET;User ID=sa")]
        public string BRITANICO_SACNETConnectionString6 {
            get {
                return ((string)(this["BRITANICO_SACNETConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ATENEA;Initial Catalog=Spring;User ID=tscreen")]
        public string SpringConnectionString {
            get {
                return ((string)(this["SpringConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTSRV09\\SQLSRV2005DEV;Initial Catalog=BRITANICO_SACNET;User ID=sa;Pa" +
            "ssword=pass@word05")]
        public string BRITANICO_SACNETConnectionString7 {
            get {
                return ((string)(this["BRITANICO_SACNETConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ATENEA;Initial Catalog=Spring;Persist Security Info=True;User ID=tscr" +
            "een")]
        public string SpringConnectionString1 {
            get {
                return ((string)(this["SpringConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVSISTEMAS;Initial Catalog=springa;User ID=sa;Password=zxcxcvzxc")]
        public string springaConnectionString {
            get {
                return ((string)(this["springaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVSISTEMAS;Initial Catalog=springjo;User ID=sa")]
        public string springjoConnectionString {
            get {
                return ((string)(this["springjoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVSISTEMAS;Initial Catalog=springh;Integrated Security=True")]
        public string springhConnectionString {
            get {
                return ((string)(this["springhConnectionString"]));
            }
        }
    }
}
