<%@ page language="C#" masterpagefile="~/MasterPage.master" autoeventwireup="true" inherits="Seguridad_frm_usuario, App_Web_0wjpmfv7" title="CENTRO CULTURAL BRITANICO - ADMINISTRADOR DE CONTENIDOS" stylesheettheme="SkinBritanico" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphPrincipal" Runat="Server">
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
<asp:Label id="Label1" runat="server" Text="ACTUALIZANDO MIS DATOS" SkinID="lblTitulos"></asp:Label><BR />&nbsp;<ajaxToolkit:TabContainer id="tcUsuario" runat="server" Height="180px" BackColor="Red" Width="650px" ActiveTabIndex="0" AutoPostBack="True" OnActiveTabChanged="tcUsuario_ActiveTabChanged" OnLoad="tcUsuario_Load" CssClass><ajaxToolkit:TabPanel runat="server" HeaderText="TabPanel1" ID="TabPanel1"><HeaderTemplate>
<asp:Label id="Label4" runat="server" Text="Clave" Width="37px" SkinID="camposNombre" __designer:wfdid="w712"></asp:Label> 
</HeaderTemplate>
<ContentTemplate>
<BR /><asp:Panel id="pClave" runat="server" Height="60px" SkinID="paneles" __designer:wfdid="w713" __designer:errorcontrol="'' could not be set on property 'TextStrengthDescriptions'."><asp:Label id="Label10" runat="server" Text="Modificando Clave de Acceso" Width="400px" __designer:wfdid="w714"></asp:Label> <BR /><BR /><TABLE style="WIDTH: 443px; HEIGHT: 87px" cellSpacing=0 cellPadding=0 border=0><TBODY><TR><TD style="WIDTH: 121px" align=right><asp:Label id="Label9" runat="server" Text="Nueva Clave:" Width="81px" SkinID="camposNombre" __designer:wfdid="w715"></asp:Label> </TD><TD style="WIDTH: 10px" align=left></TD><TD style="WIDTH: 480px" align=left><asp:TextBox id="txtClave" runat="server" Width="200px" SkinID="Textos" __designer:wfdid="w716" TextMode="Password"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator5" runat="server" ForeColor="" SkinID="rfvError" __designer:wfdid="w717" ValidationGroup="Clave" ErrorMessage="*" ControlToValidate="txtClave"></asp:RequiredFieldValidator> </TD></TR><TR><TD style="WIDTH: 121px" align=right><asp:Label id="Label5" runat="server" Text="Confirma Clave:" Width="93px" SkinID="camposNombre" __designer:wfdid="w718"></asp:Label> </TD><TD style="WIDTH: 10px" align=left></TD><TD style="WIDTH: 480px" align=left><asp:TextBox id="txtConfirmaClave" runat="server" Width="200px" SkinID="Textos" __designer:wfdid="w719" TextMode="Password"></asp:TextBox> <asp:CompareValidator id="CompareValidator1" runat="server" ForeColor="" SkinID="cvError" __designer:wfdid="w720" ValidationGroup="Clave" ErrorMessage="*" ControlToValidate="txtConfirmaClave" ToolTip="Claves deben coincidir" ControlToCompare="txtClave"></asp:CompareValidator> <asp:RequiredFieldValidator id="RequiredFieldValidator6" runat="server" ForeColor="" SkinID="rfvError" __designer:wfdid="w721" ValidationGroup="Clave" ErrorMessage="*" ControlToValidate="txtConfirmaClave"></asp:RequiredFieldValidator> </TD></TR><TR><TD style="WIDTH: 121px"></TD><TD style="WIDTH: 10px" align=left></TD><TD style="WIDTH: 480px" align=left><asp:ImageButton id="btnCGuardar" onclick="btnCGuardar_Click" runat="server" SkinID="Guardar" __designer:wfdid="w722" ValidationGroup="Clave"></asp:ImageButton> </TD></TR></TBODY></TABLE>&nbsp;&nbsp;&nbsp;<BR />&nbsp; &nbsp; &nbsp; </asp:Panel> &nbsp; &nbsp; &nbsp; 
</ContentTemplate>
</ajaxToolkit:TabPanel>
<ajaxToolkit:TabPanel runat="server" HeaderText="TabPanel2" ID="TabPanel2"><HeaderTemplate>
<asp:Label id="Label3" runat="server" Text="| &nbsp;&nbsp;&nbsp;Mail" Width="50px" SkinID="camposNombre" __designer:wfdid="w705"></asp:Label> 
</HeaderTemplate>
<ContentTemplate>
<BR /><asp:Panel id="pEmail" runat="server" Height="50px" SkinID="paneles" __designer:wfdid="w706"><asp:Label id="Label11" runat="server" Text="Modificando Email de Contacto" Width="400px" __designer:wfdid="w707"></asp:Label> <BR /><BR /><TABLE style="WIDTH: 400px" cellSpacing=0 cellPadding=0 border=0><TBODY><TR><TD style="WIDTH: 100px; TEXT-ALIGN: right" vAlign=top><asp:Label id="Label7" runat="server" Text="Nuevo Email:" Width="88px" SkinID="camposNombre" __designer:wfdid="w708"></asp:Label> </TD><TD style="WIDTH: 300px; TEXT-ALIGN: left"><asp:TextBox id="txtEmail" runat="server" Width="239px" SkinID="Textos" __designer:wfdid="w709" ValidationGroup="Email"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator7" runat="server" ForeColor="" SkinID="rfvError" __designer:wfdid="w710" ValidationGroup="Email" ErrorMessage="*" ControlToValidate="txtEmail"></asp:RequiredFieldValidator> &nbsp;&nbsp;</TD></TR><TR><TD style="WIDTH: 100px; TEXT-ALIGN: right"></TD><TD style="WIDTH: 300px; TEXT-ALIGN: left"><asp:ImageButton id="btnEGuardar" onclick="btnEGuardar_Click" runat="server" SkinID="Guardar" __designer:wfdid="w711" ValidationGroup="Email"></asp:ImageButton> </TD></TR></TBODY></TABLE></asp:Panel> 
</ContentTemplate>
</ajaxToolkit:TabPanel>
<ajaxToolkit:TabPanel runat="server" HeaderText="TabPanel3" ID="TabPanel3"><HeaderTemplate>
<asp:Label id="Label2" runat="server" Text="|&nbsp;&nbsp;&nbsp; Login" Width="50px" SkinID="camposNombre" __designer:wfdid="w690"></asp:Label> &nbsp; 
</HeaderTemplate>
<ContentTemplate>
<BR /><asp:Panel id="pUsuario" runat="server" Height="50px" SkinID="paneles" __designer:wfdid="w691"><asp:Label id="Label6" runat="server" Text="Modificando Usuario de Acceso" Width="400px" SkinID="camposNombre" __designer:wfdid="w692"></asp:Label> <BR /><BR /><TABLE style="WIDTH: 400px" cellSpacing=0 cellPadding=0 border=0><TBODY><TR><TD style="WIDTH: 100px; HEIGHT: 16px; TEXT-ALIGN: right" vAlign=top align=right><asp:Label id="Label8" runat="server" Text="Nuevo Usuario:" Width="90px" SkinID="camposNombre" __designer:wfdid="w693"></asp:Label> </TD><TD style="WIDTH: 300px; HEIGHT: 16px; TEXT-ALIGN: left"><asp:TextBox id="txtLogin" runat="server" SkinID="Textos" AutoPostBack="True" __designer:wfdid="w694" OnTextChanged="txtLogin_TextChanged"></asp:TextBox> &nbsp; <asp:RequiredFieldValidator id="RequiredFieldValidator4" runat="server" ForeColor="" SkinID="rfvError" __designer:wfdid="w695" ValidationGroup="Usuario" ErrorMessage="*" ControlToValidate="txtLogin"></asp:RequiredFieldValidator> &nbsp; </TD></TR><TR><TD style="WIDTH: 100px; HEIGHT: 16px; TEXT-ALIGN: right" align=right></TD><TD style="WIDTH: 300px; HEIGHT: 16px; TEXT-ALIGN: left">&nbsp;<asp:Label id="lblVerificaLogin" runat="server" Height="15px" Width="228px" SkinID="tError" __designer:wfdid="w696"></asp:Label> </TD></TR><TR><TD style="WIDTH: 100px; HEIGHT: 16px; TEXT-ALIGN: right" align=right></TD><TD style="WIDTH: 300px; HEIGHT: 16px; TEXT-ALIGN: left"><asp:ImageButton id="btnUGuardar" onclick="btnUGuardar_Click" runat="server" SkinID="Guardar" __designer:wfdid="w697" ValidationGroup="Usuario"></asp:ImageButton> </TD></TR></TBODY></TABLE><BR /></asp:Panel> 
</ContentTemplate>
</ajaxToolkit:TabPanel>
</ajaxToolkit:TabContainer> <asp:Label id="lblMensaje" runat="server" Width="400px" SkinID="tError"></asp:Label> 
</ContentTemplate>
    </asp:UpdatePanel>
   
</asp:Content>

