<?xml version="1.0" encoding="utf-8"?>
<Database Name="springh" Class="_ReportesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SRVSISTEMAS;Initial Catalog=springh;Integrated Security=True" SettingsObjectName="Britanico.SacNet.DataAccess.Properties.Settings" SettingsPropertyName="springhConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Sacnet.pa_rep_RankingTitulos" Method="pa_rep_RankingTitulos">
    <Parameter Name="p_CodSAC" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_CodTipoMaterial" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="p_FechaInicio" Type="System.String" DbType="Char(8)" />
    <Parameter Name="p_FechaFin" Type="System.String" DbType="Char(8)" />
    <Parameter Name="p_CodTipoMovimiento" Type="System.Char" DbType="VarChar(1)" />
    <ElementType Name="pa_rep_RankingTitulosResult">
      <Column Name="CodSAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodItem" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoMaterial" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Ejemplares" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Movimientos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Sacnet.pa_rep_TitulosMayorRetraso" Method="pa_rep_TitulosMayorRetraso">
    <Parameter Name="p_CodSAC" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_CodTipoMaterial" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="p_FechaInicio" Type="System.String" DbType="Char(8)" />
    <Parameter Name="p_FechaFin" Type="System.String" DbType="Char(8)" />
    <ElementType Name="pa_rep_TitulosMayorRetrasoResult">
      <Column Name="CodSAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodItem" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoMaterial" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Retrasos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiasRetrasos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Sacnet.pa_rep_RankingUsuarios" Method="pa_rep_RankingUsuarios">
    <Parameter Name="p_CodSAC" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_CodTipoUsuario" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="p_FechaInicio" Type="System.String" DbType="Char(8)" />
    <Parameter Name="p_FechaFin" Type="System.String" DbType="Char(8)" />
    <ElementType Name="pa_rep_RankingUsuariosResult">
      <Column Name="CodSAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoUsuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodUsuario" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EnSala" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnDomicilio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Prestamos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Sacnet.pa_rep_MovimientoXPeriodoDetallado" Method="pa_rep_MovimientoXPeriodoDetallado">
    <Parameter Name="p_CodSAC" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_CodTipoMaterial" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="p_CodTipoMovimiento" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="p_FechaInicio" Type="System.String" DbType="Char(8)" />
    <Parameter Name="p_FechaFin" Type="System.String" DbType="Char(8)" />
    <ElementType Name="pa_rep_MovimientoXPeriodoDetalladoResult">
      <Column Name="CodSAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodItem" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoMaterial" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PrestamoEn" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaMovimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TipoMovimiento" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="CodUsuarioSAC" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CodEjemplar" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Sacnet.pa_rep_StockXSAC" Method="pa_rep_StockXSAC">
    <Parameter Name="p_CodSAC" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_CodTipoMaterial" Type="System.String" DbType="VarChar(17)" />
    <ElementType Name="pa_rep_StockXSACResult">
      <Column Name="CodSAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodItem" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Item" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Prestados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reservados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Disponibles" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Asignados" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Sacnet.pa_rep_StockXSACDet" Method="pa_rep_StockXSACDet">
    <Parameter Name="p_CodSAC" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_CodTipoMaterial" Type="System.String" DbType="VarChar(17)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Sacnet.pa_rep_CarnetsXSAC" Method="pa_rep_CarnetsXSAC">
    <Parameter Name="prm_sEstablecimientoCodigo" Type="System.String" DbType="Char(4)" />
    <Parameter Name="prm_sCodArguEstado" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_dFechaProcesoINI" Type="System.String" DbType="Char(8)" />
    <Parameter Name="prm_dFechaProcesoFIN" Type="System.String" DbType="Char(8)" />
    <Return Type="System.Int32" />
  </Function>
</Database>