#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3625
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Britanico.SacNet.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="springh")]
	public partial class _ReportesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public _ReportesDataContext() : 
				base(global::Britanico.SacNet.DataAccess.Properties.Settings.Default.springhConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public _ReportesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ReportesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ReportesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ReportesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="Sacnet.pa_rep_RankingTitulos")]
		public ISingleResult<pa_rep_RankingTitulosResult> pa_rep_RankingTitulos([Parameter(DbType="VarChar(10)")] string p_CodSAC, [Parameter(DbType="VarChar(17)")] string p_CodTipoMaterial, [Parameter(DbType="Char(8)")] string p_FechaInicio, [Parameter(DbType="Char(8)")] string p_FechaFin, [Parameter(DbType="VarChar(1)")] System.Nullable<char> p_CodTipoMovimiento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodSAC, p_CodTipoMaterial, p_FechaInicio, p_FechaFin, p_CodTipoMovimiento);
			return ((ISingleResult<pa_rep_RankingTitulosResult>)(result.ReturnValue));
		}
		
		[Function(Name="Sacnet.pa_rep_TitulosMayorRetraso")]
		public ISingleResult<pa_rep_TitulosMayorRetrasoResult> pa_rep_TitulosMayorRetraso([Parameter(DbType="VarChar(10)")] string p_CodSAC, [Parameter(DbType="VarChar(17)")] string p_CodTipoMaterial, [Parameter(DbType="Char(8)")] string p_FechaInicio, [Parameter(DbType="Char(8)")] string p_FechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodSAC, p_CodTipoMaterial, p_FechaInicio, p_FechaFin);
			return ((ISingleResult<pa_rep_TitulosMayorRetrasoResult>)(result.ReturnValue));
		}
		
		[Function(Name="Sacnet.pa_rep_RankingUsuarios")]
		public ISingleResult<pa_rep_RankingUsuariosResult> pa_rep_RankingUsuarios([Parameter(DbType="VarChar(10)")] string p_CodSAC, [Parameter(DbType="VarChar(2)")] string p_CodTipoUsuario, [Parameter(DbType="Char(8)")] string p_FechaInicio, [Parameter(DbType="Char(8)")] string p_FechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodSAC, p_CodTipoUsuario, p_FechaInicio, p_FechaFin);
			return ((ISingleResult<pa_rep_RankingUsuariosResult>)(result.ReturnValue));
		}
		
		[Function(Name="Sacnet.pa_rep_MovimientoXPeriodoDetallado")]
		public ISingleResult<pa_rep_MovimientoXPeriodoDetalladoResult> pa_rep_MovimientoXPeriodoDetallado([Parameter(DbType="VarChar(10)")] string p_CodSAC, [Parameter(DbType="VarChar(17)")] string p_CodTipoMaterial, [Parameter(DbType="VarChar(2)")] string p_CodTipoMovimiento, [Parameter(DbType="Char(8)")] string p_FechaInicio, [Parameter(DbType="Char(8)")] string p_FechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodSAC, p_CodTipoMaterial, p_CodTipoMovimiento, p_FechaInicio, p_FechaFin);
			return ((ISingleResult<pa_rep_MovimientoXPeriodoDetalladoResult>)(result.ReturnValue));
		}
		
		[Function(Name="Sacnet.pa_rep_StockXSAC")]
		public ISingleResult<pa_rep_StockXSACResult> pa_rep_StockXSAC([Parameter(DbType="VarChar(10)")] string p_CodSAC, [Parameter(DbType="VarChar(17)")] string p_CodTipoMaterial)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodSAC, p_CodTipoMaterial);
			return ((ISingleResult<pa_rep_StockXSACResult>)(result.ReturnValue));
		}
		
		[Function(Name="Sacnet.pa_rep_StockXSACDet")]
        public ISingleResult<pa_rep_StockXSACDetResult> pa_rep_StockXSACDet([Parameter(DbType = "VarChar(10)")] string p_CodSAC, [Parameter(DbType = "VarChar(17)")] string p_CodTipoMaterial)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodSAC, p_CodTipoMaterial);
            return ((ISingleResult<pa_rep_StockXSACDetResult>)(result.ReturnValue));
		}
		
		[Function(Name="Sacnet.pa_rep_CarnetsXSAC")]
        public ISingleResult<pa_rep_CarnetsXSACResult> pa_rep_CarnetsXSAC([Parameter(DbType = "Char(4)")] string prm_sEstablecimientoCodigo, [Parameter(DbType = "VarChar(17)")] string prm_sCodArguEstado, [Parameter(DbType = "Char(8)")] string prm_dFechaProcesoINI, [Parameter(DbType = "Char(8)")] string prm_dFechaProcesoFIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_sEstablecimientoCodigo, prm_sCodArguEstado, prm_dFechaProcesoINI, prm_dFechaProcesoFIN);
            return ((ISingleResult<pa_rep_CarnetsXSACResult>)(result.ReturnValue));
		}
	}
	
	public partial class pa_rep_RankingTitulosResult
	{
		
		private string _CodSAC;
		
		private string _SAC;
		
		private string _CodItem;
		
		private string _Item;
		
		private string _TipoMaterial;
		
		private System.Nullable<int> _Ejemplares;
		
		private int _Movimientos;
		
		public pa_rep_RankingTitulosResult()
		{
		}
		
		[Column(Storage="_CodSAC", DbType="VarChar(50)")]
		public string CodSAC
		{
			get
			{
				return this._CodSAC;
			}
			set
			{
				if ((this._CodSAC != value))
				{
					this._CodSAC = value;
				}
			}
		}
		
		[Column(Storage="_SAC", DbType="VarChar(50)")]
		public string SAC
		{
			get
			{
				return this._SAC;
			}
			set
			{
				if ((this._SAC != value))
				{
					this._SAC = value;
				}
			}
		}
		
		[Column(Storage="_CodItem", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodItem
		{
			get
			{
				return this._CodItem;
			}
			set
			{
				if ((this._CodItem != value))
				{
					this._CodItem = value;
				}
			}
		}
		
		[Column(Storage="_Item", DbType="VarChar(200)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this._Item = value;
				}
			}
		}
		
		[Column(Storage="_TipoMaterial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TipoMaterial
		{
			get
			{
				return this._TipoMaterial;
			}
			set
			{
				if ((this._TipoMaterial != value))
				{
					this._TipoMaterial = value;
				}
			}
		}
		
		[Column(Storage="_Ejemplares", DbType="Int")]
		public System.Nullable<int> Ejemplares
		{
			get
			{
				return this._Ejemplares;
			}
			set
			{
				if ((this._Ejemplares != value))
				{
					this._Ejemplares = value;
				}
			}
		}
		
		[Column(Storage="_Movimientos", DbType="Int NOT NULL")]
		public int Movimientos
		{
			get
			{
				return this._Movimientos;
			}
			set
			{
				if ((this._Movimientos != value))
				{
					this._Movimientos = value;
				}
			}
		}
	}
	
	public partial class pa_rep_TitulosMayorRetrasoResult
	{
		
		private string _CodSAC;
		
		private string _SAC;
		
		private string _CodItem;
		
		private string _Item;
		
		private string _TipoMaterial;
		
		private System.Nullable<int> _Retrasos;
		
		private System.Nullable<int> _DiasRetrasos;
		
		public pa_rep_TitulosMayorRetrasoResult()
		{
		}
		
		[Column(Storage="_CodSAC", DbType="VarChar(50)")]
		public string CodSAC
		{
			get
			{
				return this._CodSAC;
			}
			set
			{
				if ((this._CodSAC != value))
				{
					this._CodSAC = value;
				}
			}
		}
		
		[Column(Storage="_SAC", DbType="VarChar(50)")]
		public string SAC
		{
			get
			{
				return this._SAC;
			}
			set
			{
				if ((this._SAC != value))
				{
					this._SAC = value;
				}
			}
		}
		
		[Column(Storage="_CodItem", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodItem
		{
			get
			{
				return this._CodItem;
			}
			set
			{
				if ((this._CodItem != value))
				{
					this._CodItem = value;
				}
			}
		}
		
		[Column(Storage="_Item", DbType="VarChar(200)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this._Item = value;
				}
			}
		}
		
		[Column(Storage="_TipoMaterial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TipoMaterial
		{
			get
			{
				return this._TipoMaterial;
			}
			set
			{
				if ((this._TipoMaterial != value))
				{
					this._TipoMaterial = value;
				}
			}
		}
		
		[Column(Storage="_Retrasos", DbType="Int")]
		public System.Nullable<int> Retrasos
		{
			get
			{
				return this._Retrasos;
			}
			set
			{
				if ((this._Retrasos != value))
				{
					this._Retrasos = value;
				}
			}
		}
		
		[Column(Storage="_DiasRetrasos", DbType="Int")]
		public System.Nullable<int> DiasRetrasos
		{
			get
			{
				return this._DiasRetrasos;
			}
			set
			{
				if ((this._DiasRetrasos != value))
				{
					this._DiasRetrasos = value;
				}
			}
		}
	}
	
	public partial class pa_rep_RankingUsuariosResult
	{
		
		private string _CodSAC;
		
		private string _SAC;
		
		private string _TipoUsuario;
		
		private string _CodUsuario;
		
		private string _Usuario;
		
		private System.Nullable<int> _EnSala;
		
		private System.Nullable<int> _EnDomicilio;
		
		private System.Nullable<int> _Prestamos;
		
		public pa_rep_RankingUsuariosResult()
		{
		}
		
		[Column(Storage="_CodSAC", DbType="VarChar(50)")]
		public string CodSAC
		{
			get
			{
				return this._CodSAC;
			}
			set
			{
				if ((this._CodSAC != value))
				{
					this._CodSAC = value;
				}
			}
		}
		
		[Column(Storage="_SAC", DbType="VarChar(50)")]
		public string SAC
		{
			get
			{
				return this._SAC;
			}
			set
			{
				if ((this._SAC != value))
				{
					this._SAC = value;
				}
			}
		}
		
		[Column(Storage="_TipoUsuario", DbType="VarChar(50)")]
		public string TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this._TipoUsuario = value;
				}
			}
		}
		
		[Column(Storage="_CodUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this._CodUsuario = value;
				}
			}
		}
		
		[Column(Storage="_Usuario", DbType="VarChar(100)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[Column(Storage="_EnSala", DbType="Int")]
		public System.Nullable<int> EnSala
		{
			get
			{
				return this._EnSala;
			}
			set
			{
				if ((this._EnSala != value))
				{
					this._EnSala = value;
				}
			}
		}
		
		[Column(Storage="_EnDomicilio", DbType="Int")]
		public System.Nullable<int> EnDomicilio
		{
			get
			{
				return this._EnDomicilio;
			}
			set
			{
				if ((this._EnDomicilio != value))
				{
					this._EnDomicilio = value;
				}
			}
		}
		
		[Column(Storage="_Prestamos", DbType="Int")]
		public System.Nullable<int> Prestamos
		{
			get
			{
				return this._Prestamos;
			}
			set
			{
				if ((this._Prestamos != value))
				{
					this._Prestamos = value;
				}
			}
		}
	}
	
	public partial class pa_rep_MovimientoXPeriodoDetalladoResult
	{
		
		private string _CodSAC;
		
		private string _SAC;
		
		private string _CodItem;
		
		private string _Item;
		
		private string _TipoMaterial;
		
		private string _PrestamoEn;
		
		private System.Nullable<System.DateTime> _FechaMovimiento;
		
		private string _TipoMovimiento;
		
		private string _CodUsuarioSAC;
		
		private string _CodEjemplar;
		
		public pa_rep_MovimientoXPeriodoDetalladoResult()
		{
		}
		
		[Column(Storage="_CodSAC", DbType="VarChar(50)")]
		public string CodSAC
		{
			get
			{
				return this._CodSAC;
			}
			set
			{
				if ((this._CodSAC != value))
				{
					this._CodSAC = value;
				}
			}
		}
		
		[Column(Storage="_SAC", DbType="VarChar(50)")]
		public string SAC
		{
			get
			{
				return this._SAC;
			}
			set
			{
				if ((this._SAC != value))
				{
					this._SAC = value;
				}
			}
		}
		
		[Column(Storage="_CodItem", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodItem
		{
			get
			{
				return this._CodItem;
			}
			set
			{
				if ((this._CodItem != value))
				{
					this._CodItem = value;
				}
			}
		}
		
		[Column(Storage="_Item", DbType="VarChar(200)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this._Item = value;
				}
			}
		}
		
		[Column(Storage="_TipoMaterial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TipoMaterial
		{
			get
			{
				return this._TipoMaterial;
			}
			set
			{
				if ((this._TipoMaterial != value))
				{
					this._TipoMaterial = value;
				}
			}
		}
		
		[Column(Storage="_PrestamoEn", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PrestamoEn
		{
			get
			{
				return this._PrestamoEn;
			}
			set
			{
				if ((this._PrestamoEn != value))
				{
					this._PrestamoEn = value;
				}
			}
		}
		
		[Column(Storage="_FechaMovimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaMovimiento
		{
			get
			{
				return this._FechaMovimiento;
			}
			set
			{
				if ((this._FechaMovimiento != value))
				{
					this._FechaMovimiento = value;
				}
			}
		}
		
		[Column(Storage="_TipoMovimiento", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string TipoMovimiento
		{
			get
			{
				return this._TipoMovimiento;
			}
			set
			{
				if ((this._TipoMovimiento != value))
				{
					this._TipoMovimiento = value;
				}
			}
		}
		
		[Column(Storage="_CodUsuarioSAC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodUsuarioSAC
		{
			get
			{
				return this._CodUsuarioSAC;
			}
			set
			{
				if ((this._CodUsuarioSAC != value))
				{
					this._CodUsuarioSAC = value;
				}
			}
		}
		
		[Column(Storage="_CodEjemplar", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string CodEjemplar
		{
			get
			{
				return this._CodEjemplar;
			}
			set
			{
				if ((this._CodEjemplar != value))
				{
					this._CodEjemplar = value;
				}
			}
		}
	}
	
	public partial class pa_rep_StockXSACResult
	{
		
		private string _CodSAC;
		
		private string _SAC;
		
		private string _CodItem;
		
		private string _Item;

        private string _FormatoAdicional;

		private System.Nullable<int> _Prestados;
		
		private System.Nullable<int> _Reservados;
		
		private System.Nullable<int> _Disponibles;
		
		private System.Nullable<int> _Asignados;

        private string _sCodArguTema;

        private string _Tema;
		
		public pa_rep_StockXSACResult()
		{
		}
		
		[Column(Storage="_CodSAC", DbType="VarChar(50)")]
		public string CodSAC
		{
			get
			{
				return this._CodSAC;
			}
			set
			{
				if ((this._CodSAC != value))
				{
					this._CodSAC = value;
				}
			}
		}
		
		[Column(Storage="_SAC", DbType="VarChar(50)")]
		public string SAC
		{
			get
			{
				return this._SAC;
			}
			set
			{
				if ((this._SAC != value))
				{
					this._SAC = value;
				}
			}
		}
		
		[Column(Storage="_CodItem", DbType="VarChar(20)")]
		public string CodItem
		{
			get
			{
				return this._CodItem;
			}
			set
			{
				if ((this._CodItem != value))
				{
					this._CodItem = value;
				}
			}
		}
		
		[Column(Storage="_Item", DbType="VarChar(200)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this._Item = value;
				}
			}
		}

        [Column(Storage = "_FormatoAdicional", DbType = "VarChar(100)")]
        public string FormatoAdicional
        {
            get
            {
                return this._FormatoAdicional;
            }
            set
            {
                if ((this._FormatoAdicional != value))
                {
                    this._FormatoAdicional = value;
                }
            }
        }

		[Column(Storage="_Prestados", DbType="Int")]
		public System.Nullable<int> Prestados
		{
			get
			{
				return this._Prestados;
			}
			set
			{
				if ((this._Prestados != value))
				{
					this._Prestados = value;
				}
			}
		}
		
		[Column(Storage="_Reservados", DbType="Int")]
		public System.Nullable<int> Reservados
		{
			get
			{
				return this._Reservados;
			}
			set
			{
				if ((this._Reservados != value))
				{
					this._Reservados = value;
				}
			}
		}
		
		[Column(Storage="_Disponibles", DbType="Int")]
		public System.Nullable<int> Disponibles
		{
			get
			{
				return this._Disponibles;
			}
			set
			{
				if ((this._Disponibles != value))
				{
					this._Disponibles = value;
				}
			}
		}
		
		[Column(Storage="_Asignados", DbType="Int")]
		public System.Nullable<int> Asignados
		{
			get
			{
				return this._Asignados;
			}
			set
			{
				if ((this._Asignados != value))
				{
					this._Asignados = value;
				}
			}
		}

        [Column(Storage = "_sCodArguTema", DbType = "VarChar(50)")]
        public string sCodArguTema
        {
            get
            {
                return this._sCodArguTema;
            }
            set
            {
                if ((this._sCodArguTema != value))
                {
                    this._sCodArguTema = value;
                }
            }
        }

        [Column(Storage = "_Tema", DbType = "VarChar(50)")]
        public string Tema
        {
            get
            {
                return this._Tema;
            }
            set
            {
                if ((this._Tema != value))
                {
                    this._Tema = value;
                }
            }
        }
	}

    public partial class pa_rep_StockXSACDetResult
    {
        

        private string _CodSAC;

        private string _SAC;

        private string _CodItem;

        private string _Item;

        private string _Ejemplar;

        private string _FormatoAdicional;

        private System.Nullable<int> _Prestados;

        private System.Nullable<int> _Reservados;

        private System.Nullable<int> _Disponibles;

        private System.Nullable<int> _Asignados;

        private string _sCodArguTema;

        private string _Tema;

        public pa_rep_StockXSACDetResult()
        {
        }

        [Column(Storage = "_CodSAC", DbType = "VarChar(50)")]
        public string CodSAC
        {
            get
            {
                return this._CodSAC;
            }
            set
            {
                if ((this._CodSAC != value))
                {
                    this._CodSAC = value;
                }
            }
        }

        [Column(Storage = "_SAC", DbType = "VarChar(50)")]
        public string SAC
        {
            get
            {
                return this._SAC;
            }
            set
            {
                if ((this._SAC != value))
                {
                    this._SAC = value;
                }
            }
        }

        [Column(Storage = "_CodItem", DbType = "VarChar(20)")]
        public string CodItem
        {
            get
            {
                return this._CodItem;
            }
            set
            {
                if ((this._CodItem != value))
                {
                    this._CodItem = value;
                }
            }
        }

        [Column(Storage = "_Item", DbType = "VarChar(200)")]
        public string Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                if ((this._Item != value))
                {
                    this._Item = value;
                }
            }
        }

        [Column(Storage = "_Ejemplar", DbType = "VarChar(50)")]
        public string Ejemplar
        {
            get
            {
                return this._Ejemplar;
            }
            set
            {
                if ((this._Ejemplar != value))
                {
                    this._Ejemplar = value;
                }
            }
        }


        [Column(Storage = "_FormatoAdicional", DbType = "VarChar(100)")]
        public string FormatoAdicional
        {
            get
            {
                return this._FormatoAdicional;
            }
            set
            {
                if ((this._FormatoAdicional != value))
                {
                    this._FormatoAdicional = value;
                }
            }
        }

        [Column(Storage = "_Prestados", DbType = "Int")]
        public System.Nullable<int> Prestados
        {
            get
            {
                return this._Prestados;
            }
            set
            {
                if ((this._Prestados != value))
                {
                    this._Prestados = value;
                }
            }
        }

        [Column(Storage = "_Reservados", DbType = "Int")]
        public System.Nullable<int> Reservados
        {
            get
            {
                return this._Reservados;
            }
            set
            {
                if ((this._Reservados != value))
                {
                    this._Reservados = value;
                }
            }
        }

        [Column(Storage = "_Disponibles", DbType = "Int")]
        public System.Nullable<int> Disponibles
        {
            get
            {
                return this._Disponibles;
            }
            set
            {
                if ((this._Disponibles != value))
                {
                    this._Disponibles = value;
                }
            }
        }

        [Column(Storage = "_Asignados", DbType = "Int")]
        public System.Nullable<int> Asignados
        {
            get
            {
                return this._Asignados;
            }
            set
            {
                if ((this._Asignados != value))
                {
                    this._Asignados = value;
                }
            }
        }

        [Column(Storage = "_sCodArguTema", DbType = "VarChar(50)")]
        public string sCodArguTema
        {
            get
            {
                return this._sCodArguTema;
            }
            set
            {
                if ((this._sCodArguTema != value))
                {
                    this._sCodArguTema = value;
                }
            }
        }

        [Column(Storage = "_Tema", DbType = "VarChar(50)")]
        public string Tema
        {
            get
            {
                return this._Tema;
            }
            set
            {
                if ((this._Tema != value))
                {
                    this._Tema = value;
                }
            }
        }
    }

    public partial class pa_rep_CarnetsXSACResult
    {

        private string _SAC;

        private string _EstadoCarnet;

        private string _CodUsuario;

        private string _Usuario;

        private string _Curso;

        private string _Horario;

        private string _Aula;

        private string _Subsistema;

        public pa_rep_CarnetsXSACResult()
        {
        }

        [Column(Storage = "_SAC", DbType = "Char(30)")]
        public string SAC
        {
            get
            {
                return this._SAC;
            }
            set
            {
                if ((this._SAC != value))
                {
                    this._SAC = value;
                }
            }
        }

        [Column(Storage = "_EstadoCarnet", DbType = "VarChar(100)")]
        public string EstadoCarnet
        {
            get
            {
                return this._EstadoCarnet;
            }
            set
            {
                if ((this._EstadoCarnet != value))
                {
                    this._EstadoCarnet = value;
                }
            }
        }

        [Column(Storage = "_CodUsuario", DbType = "VarChar(20) NOT NULL", CanBeNull = false)]
        public string CodUsuario
        {
            get
            {
                return this._CodUsuario;
            }
            set
            {
                if ((this._CodUsuario != value))
                {
                    this._CodUsuario = value;
                }
            }
        }

        [Column(Storage = "_Usuario", DbType = "VarChar(101) NOT NULL", CanBeNull = false)]
        public string Usuario
        {
            get
            {
                return this._Usuario;
            }
            set
            {
                if ((this._Usuario != value))
                {
                    this._Usuario = value;
                }
            }
        }

        [Column(Storage = "_Curso", DbType = "VarChar(20)")]
        public string Curso
        {
            get
            {
                return this._Curso;
            }
            set
            {
                if ((this._Curso != value))
                {
                    this._Curso = value;
                }
            }
        }

        [Column(Storage = "_Horario", DbType = "VarChar(20)")]
        public string Horario
        {
            get
            {
                return this._Horario;
            }
            set
            {
                if ((this._Horario != value))
                {
                    this._Horario = value;
                }
            }
        }

        [Column(Storage = "_Aula", DbType = "VarChar(20)")]
        public string Aula
        {
            get
            {
                return this._Aula;
            }
            set
            {
                if ((this._Aula != value))
                {
                    this._Aula = value;
                }
            }
        }

        [Column(Storage = "_Subsistema", DbType = "VarChar(20)")]
        public string Subsistema
        {
            get
            {
                return this._Subsistema;
            }
            set
            {
                if ((this._Subsistema != value))
                {
                    this._Subsistema = value;
                }
            }
        }
    }

}
#pragma warning restore 1591
