#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Britanico.SacNet.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Spring")]
	public partial class _SEGURIDADDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public _SEGURIDADDataContext() : 
				base(global::Britanico.SacNet.DataAccess.Properties.Settings.Default.SpringConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public _SEGURIDADDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _SEGURIDADDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _SEGURIDADDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _SEGURIDADDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="Ssi.pa_pro_ListarMenuPorRolUsuario")]
		public ISingleResult<pa_pro_ListarMenuPorRolUsuarioResult> pa_pro_ListarMenuPorRolUsuario([Parameter(DbType="VarChar(4)")] string p_CodigoRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol);
			return ((ISingleResult<pa_pro_ListarMenuPorRolUsuarioResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_pro_DetectarLoginPassword")]
		public ISingleResult<pa_pro_DetectarLoginPasswordResult> pa_pro_DetectarLoginPassword([Parameter(DbType="VarChar(20)")] string p_CodUsuario, [Parameter(DbType="VarChar(100)")] string p_Contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodUsuario, p_Contraseña);
			return ((ISingleResult<pa_pro_DetectarLoginPasswordResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_RegistrarUsuariosRoles")]
		public int pa_mnt_RegistrarUsuariosRoles([Parameter(DbType="VarChar(20)")] string p_CodigoUsuario, [Parameter(DbType="Char(3)")] string p_CodigoRol, [Parameter(DbType="Bit")] System.Nullable<bool> p_Estado, [Parameter(DbType="VarChar(20)")] string p_SegUsuarioRegistro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoUsuario, p_CodigoRol, p_Estado, p_SegUsuarioRegistro);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ListarUsuariosRoles")]
		public ISingleResult<pa_mnt_ListarUsuariosRolesResult> pa_mnt_ListarUsuariosRoles([Parameter(DbType="VarChar(20)")] string p_CodigoUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoUsuario);
			return ((ISingleResult<pa_mnt_ListarUsuariosRolesResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ListarUsuarios")]
		public ISingleResult<pa_mnt_ListarUsuariosResult> pa_mnt_ListarUsuarios([Parameter(DbType="VarChar(15)")] string p_NombresUsuario, [Parameter(DbType="VarChar(15)")] string p_ApellidosUsuario, [Parameter(DbType="VarChar(15)")] string p_LoginUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_NombresUsuario, p_ApellidosUsuario, p_LoginUsuario);
			return ((ISingleResult<pa_mnt_ListarUsuariosResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_EliminarUsuariosRoles")]
		public int pa_mnt_EliminarUsuariosRoles([Parameter(DbType="VarChar(20)")] string p_CodigoUsuario, [Parameter(DbType="Char(3)")] string p_CodigoRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoUsuario, p_CodigoRol);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_EliminarRolesOpciones")]
		public int pa_mnt_EliminarRolesOpciones([Parameter(DbType="Char(3)")] string p_CodigoRol, [Parameter(DbType="Char(4)")] string p_CodigoOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol, p_CodigoOpcion);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_EliminarRoles")]
		public int pa_mnt_EliminarRoles([Parameter(DbType="Char(3)")] string p_CodigoRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_EliminarOpciones")]
		public int pa_mnt_EliminarOpciones([Parameter(DbType="Char(4)")] string p_CodigoOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoOpcion);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_BuscarUsuariosRoles")]
		public ISingleResult<pa_mnt_BuscarUsuariosRolesResult> pa_mnt_BuscarUsuariosRoles([Parameter(DbType="VarChar(20)")] string p_CodigoUsuario, [Parameter(DbType="Char(3)")] string p_CodigoRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoUsuario, p_CodigoRol);
			return ((ISingleResult<pa_mnt_BuscarUsuariosRolesResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_BuscarRolesOpciones")]
		public ISingleResult<pa_mnt_BuscarRolesOpcionesResult> pa_mnt_BuscarRolesOpciones([Parameter(DbType="Char(3)")] string p_CodigoRol, [Parameter(DbType="Char(4)")] string p_CodigoOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol, p_CodigoOpcion);
			return ((ISingleResult<pa_mnt_BuscarRolesOpcionesResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_BuscarOpciones")]
		public ISingleResult<pa_mnt_BuscarOpcionesResult> pa_mnt_BuscarOpciones([Parameter(DbType="Char(4)")] string p_CodigoOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoOpcion);
			return ((ISingleResult<pa_mnt_BuscarOpcionesResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ActualizarUsuariosRoles")]
		public int pa_mnt_ActualizarUsuariosRoles([Parameter(DbType="VarChar(20)")] string p_CodigoUsuario, [Parameter(DbType="Char(3)")] string p_CodigoRol, [Parameter(DbType="Bit")] System.Nullable<bool> p_Estado, [Parameter(DbType="VarChar(20)")] string p_SegUsuarioModifica)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoUsuario, p_CodigoRol, p_Estado, p_SegUsuarioModifica);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ActualizarRolesOpciones")]
		public int pa_mnt_ActualizarRolesOpciones([Parameter(DbType="Char(3)")] string p_CodigoRol, [Parameter(DbType="Char(4)")] string p_CodigoOpcion, [Parameter(DbType="Bit")] System.Nullable<bool> p_Flag_Ver, [Parameter(DbType="Bit")] System.Nullable<bool> p_Flag_Eliminar, [Parameter(DbType="Bit")] System.Nullable<bool> p_Flag_Editar, [Parameter(DbType="Bit")] System.Nullable<bool> p_Flag_Nuevo, [Parameter(DbType="VarChar(20)")] string p_SegUsuarioModifica)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol, p_CodigoOpcion, p_Flag_Ver, p_Flag_Eliminar, p_Flag_Editar, p_Flag_Nuevo, p_SegUsuarioModifica);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ActualizarRoles")]
		public int pa_mnt_ActualizarRoles([Parameter(DbType="Char(3)")] string p_CodigoRol, [Parameter(DbType="VarChar(25)")] string p_NombreRol, [Parameter(DbType="VarChar(50)")] string p_DescripcionRol, [Parameter(DbType="Char(1)")] System.Nullable<char> p_Estado, [Parameter(DbType="VarChar(20)")] string p_SegUsuarioModifica)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol, p_NombreRol, p_DescripcionRol, p_Estado, p_SegUsuarioModifica);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_RegistrarRolesOpciones")]
		public int pa_mnt_RegistrarRolesOpciones([Parameter(DbType="Char(3)")] string p_CodigoRol, [Parameter(DbType="Char(4)")] string p_CodigoOpcion, [Parameter(DbType="Bit")] System.Nullable<bool> p_Flag_Ver, [Parameter(DbType="Bit")] System.Nullable<bool> p_Flag_Eliminar, [Parameter(DbType="Bit")] System.Nullable<bool> p_Flag_Editar, [Parameter(DbType="Bit")] System.Nullable<bool> p_Flag_Nuevo, [Parameter(DbType="VarChar(20)")] string p_SegUsuarioRegistro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol, p_CodigoOpcion, p_Flag_Ver, p_Flag_Eliminar, p_Flag_Editar, p_Flag_Nuevo, p_SegUsuarioRegistro);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_pro_ListarRolOpcion")]
		public ISingleResult<pa_pro_ListarRolOpcionResult> pa_pro_ListarRolOpcion([Parameter(DbType="VarChar(4)")] string p_CodigoRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol);
			return ((ISingleResult<pa_pro_ListarRolOpcionResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ListarRolesOpciones")]
		public ISingleResult<pa_mnt_ListarRolesOpcionesResult> pa_mnt_ListarRolesOpciones([Parameter(DbType="Char(3)")] string p_CodigoRol, [Parameter(DbType="Char(4)")] string p_CodigoOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol, p_CodigoOpcion);
			return ((ISingleResult<pa_mnt_ListarRolesOpcionesResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_RegistrarRoles")]
		public int pa_mnt_RegistrarRoles([Parameter(DbType="Char(3)")] ref string p_CodigoRol, [Parameter(DbType="VarChar(25)")] string p_NombreRol, [Parameter(DbType="VarChar(50)")] string p_DescripcionRol, [Parameter(DbType="Char(1)")] System.Nullable<char> p_Estado, [Parameter(DbType="VarChar(20)")] string p_SegUsuarioRegistro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol, p_NombreRol, p_DescripcionRol, p_Estado, p_SegUsuarioRegistro);
			p_CodigoRol = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Maestras.pa_mnt_ActualizarConfig")]
		public int pa_mnt_ActualizarConfig([Parameter(DbType="Char(6)")] string p_CodConfig, [Parameter(DbType="VarChar(17)")] string p_CodArgu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodConfig, p_CodArgu);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Maestras.pa_mnt_BuscarConfig")]
		public ISingleResult<pa_mnt_BuscarConfigResult> pa_mnt_BuscarConfig([Parameter(DbType="Char(6)")] string p_CodConfig)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodConfig);
			return ((ISingleResult<pa_mnt_BuscarConfigResult>)(result.ReturnValue));
		}
		
		[Function(Name="Maestras.pa_mnt_ListarConfig")]
		public ISingleResult<pa_mnt_ListarConfigResult> pa_mnt_ListarConfig([Parameter(DbType="Char(4)")] string p_CodSistema)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodSistema);
			return ((ISingleResult<pa_mnt_ListarConfigResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_BuscarUsuarios")]
		public ISingleResult<pa_mnt_BuscarUsuariosResult> pa_mnt_BuscarUsuarios([Parameter(DbType="VarChar(20)")] string p_LoginUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_LoginUsuario);
			return ((ISingleResult<pa_mnt_BuscarUsuariosResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ActualizarOpciones")]
		public int pa_mnt_ActualizarOpciones([Parameter(DbType="Char(4)")] string p_CodigoOpcion, [Parameter(DbType="Char(4)")] string p_CodigoPadre, [Parameter(DbType="VarChar(35)")] string p_Nombre, [Parameter(DbType="VarChar(50)")] string p_Descripcion, [Parameter(DbType="VarChar(100)")] string p_Enlace, [Parameter(DbType="Char(1)")] System.Nullable<char> p_FlagMenu, [Parameter(DbType="Char(1)")] System.Nullable<char> p_Estado, [Parameter(DbType="VarChar(20)")] string p_SegUsuarioModifica)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoOpcion, p_CodigoPadre, p_Nombre, p_Descripcion, p_Enlace, p_FlagMenu, p_Estado, p_SegUsuarioModifica);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_RegistrarOpciones")]
		public int pa_mnt_RegistrarOpciones([Parameter(DbType="Char(4)")] ref string p_CodigoOpcion, [Parameter(DbType="Char(4)")] string p_CodigoPadre, [Parameter(DbType="VarChar(35)")] string p_Nombre, [Parameter(DbType="VarChar(50)")] string p_Descripcion, [Parameter(DbType="VarChar(100)")] string p_Enlace, [Parameter(DbType="Char(1)")] System.Nullable<char> p_FlagMenu, [Parameter(DbType="Char(1)")] System.Nullable<char> p_Estado, [Parameter(DbType="VarChar(20)")] string p_SegUsuarioRegistro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoOpcion, p_CodigoPadre, p_Nombre, p_Descripcion, p_Enlace, p_FlagMenu, p_Estado, p_SegUsuarioRegistro);
			p_CodigoOpcion = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ListarOpciones")]
		public ISingleResult<pa_mnt_ListarOpcionesResult> pa_mnt_ListarOpciones([Parameter(DbType="VarChar(40)")] string p_NombreOpcion, [Parameter(DbType="VarChar(50)")] string p_DescripcionOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_NombreOpcion, p_DescripcionOpcion);
			return ((ISingleResult<pa_mnt_ListarOpcionesResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_pro_DetectarLogin")]
		public ISingleResult<pa_pro_DetectarLoginResult> pa_pro_DetectarLogin([Parameter(DbType="VarChar(20)")] string p_CodUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodUsuario);
			return ((ISingleResult<pa_pro_DetectarLoginResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_ListarRoles")]
		public ISingleResult<pa_mnt_ListarRolesResult> pa_mnt_ListarRoles([Parameter(DbType="VarChar(15)")] string p_NombreRol, [Parameter(DbType="VarChar(15)")] string p_DescripcionRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_NombreRol, p_DescripcionRol);
			return ((ISingleResult<pa_mnt_ListarRolesResult>)(result.ReturnValue));
		}
		
		[Function(Name="Ssi.pa_mnt_BuscarRoles")]
		public ISingleResult<pa_mnt_BuscarRolesResult> pa_mnt_BuscarRoles([Parameter(DbType="Char(3)")] string p_CodigoRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_CodigoRol);
			return ((ISingleResult<pa_mnt_BuscarRolesResult>)(result.ReturnValue));
		}
	}
	
	public partial class pa_pro_ListarMenuPorRolUsuarioResult
	{
		
		private string _CodigoOpcion;
		
		private string _CodigoPadre;
		
		private string _Nombre;
		
		private string _Enlace;
		
		private string _Descripcion;
		
		private System.Nullable<char> _FlagMenu;
		
		public pa_pro_ListarMenuPorRolUsuarioResult()
		{
		}
		
		[Column(Storage="_CodigoOpcion", DbType="Char(4)")]
		public string CodigoOpcion
		{
			get
			{
				return this._CodigoOpcion;
			}
			set
			{
				if ((this._CodigoOpcion != value))
				{
					this._CodigoOpcion = value;
				}
			}
		}
		
		[Column(Storage="_CodigoPadre", DbType="Char(4)")]
		public string CodigoPadre
		{
			get
			{
				return this._CodigoPadre;
			}
			set
			{
				if ((this._CodigoPadre != value))
				{
					this._CodigoPadre = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(25)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[Column(Storage="_Enlace", DbType="VarChar(100)")]
		public string Enlace
		{
			get
			{
				return this._Enlace;
			}
			set
			{
				if ((this._Enlace != value))
				{
					this._Enlace = value;
				}
			}
		}
		
		[Column(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[Column(Storage="_FlagMenu", DbType="Char(1)")]
		public System.Nullable<char> FlagMenu
		{
			get
			{
				return this._FlagMenu;
			}
			set
			{
				if ((this._FlagMenu != value))
				{
					this._FlagMenu = value;
				}
			}
		}
	}
	
	public partial class pa_pro_DetectarLoginPasswordResult
	{
		
		private System.Nullable<int> _Cantidad;
		
		public pa_pro_DetectarLoginPasswordResult()
		{
		}
		
		[Column(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_ListarUsuariosRolesResult
	{
		
		private string _CodigoUsuario;
		
		private string _CodigoUsuarioNombre;
		
		private string _CodigoRol;
		
		private string _CodigoRolNombre;
		
		private bool _Estado;
		
		private System.DateTime _SegFechaRegistro;
		
		private System.DateTime _SegFechaModifica;
		
		private string _SegUsuarioRegistro;
		
		private string _SegUsuarioModifica;
		
		private string _SegMaquina;
		
		public pa_mnt_ListarUsuariosRolesResult()
		{
		}
		
		[Column(Storage="_CodigoUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoUsuario
		{
			get
			{
				return this._CodigoUsuario;
			}
			set
			{
				if ((this._CodigoUsuario != value))
				{
					this._CodigoUsuario = value;
				}
			}
		}
		
		[Column(Storage="_CodigoUsuarioNombre", DbType="VarChar(82)")]
		public string CodigoUsuarioNombre
		{
			get
			{
				return this._CodigoUsuarioNombre;
			}
			set
			{
				if ((this._CodigoUsuarioNombre != value))
				{
					this._CodigoUsuarioNombre = value;
				}
			}
		}
		
		[Column(Storage="_CodigoRol", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CodigoRol
		{
			get
			{
				return this._CodigoRol;
			}
			set
			{
				if ((this._CodigoRol != value))
				{
					this._CodigoRol = value;
				}
			}
		}
		
		[Column(Storage="_CodigoRolNombre", DbType="VarChar(25)")]
		public string CodigoRolNombre
		{
			get
			{
				return this._CodigoRolNombre;
			}
			set
			{
				if ((this._CodigoRolNombre != value))
				{
					this._CodigoRolNombre = value;
				}
			}
		}
		
		[Column(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaModifica", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaModifica
		{
			get
			{
				return this._SegFechaModifica;
			}
			set
			{
				if ((this._SegFechaModifica != value))
				{
					this._SegFechaModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioModifica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioModifica
		{
			get
			{
				return this._SegUsuarioModifica;
			}
			set
			{
				if ((this._SegUsuarioModifica != value))
				{
					this._SegUsuarioModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_ListarUsuariosResult
	{
		
		private string _LoginUsuario;
		
		private string _PasswordUsuario;
		
		private string _ApellidosUsuario;
		
		private string _NombresUsuario;
		
		private string _CodPersona;
		
		private bool _EstadoUsuario;
		
		public pa_mnt_ListarUsuariosResult()
		{
		}
		
		[Column(Storage="_LoginUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginUsuario
		{
			get
			{
				return this._LoginUsuario;
			}
			set
			{
				if ((this._LoginUsuario != value))
				{
					this._LoginUsuario = value;
				}
			}
		}
		
		[Column(Storage="_PasswordUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PasswordUsuario
		{
			get
			{
				return this._PasswordUsuario;
			}
			set
			{
				if ((this._PasswordUsuario != value))
				{
					this._PasswordUsuario = value;
				}
			}
		}
		
		[Column(Storage="_ApellidosUsuario", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string ApellidosUsuario
		{
			get
			{
				return this._ApellidosUsuario;
			}
			set
			{
				if ((this._ApellidosUsuario != value))
				{
					this._ApellidosUsuario = value;
				}
			}
		}
		
		[Column(Storage="_NombresUsuario", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string NombresUsuario
		{
			get
			{
				return this._NombresUsuario;
			}
			set
			{
				if ((this._NombresUsuario != value))
				{
					this._NombresUsuario = value;
				}
			}
		}
		
		[Column(Storage="_CodPersona", DbType="VarChar(20)")]
		public string CodPersona
		{
			get
			{
				return this._CodPersona;
			}
			set
			{
				if ((this._CodPersona != value))
				{
					this._CodPersona = value;
				}
			}
		}
		
		[Column(Storage="_EstadoUsuario", DbType="Bit NOT NULL")]
		public bool EstadoUsuario
		{
			get
			{
				return this._EstadoUsuario;
			}
			set
			{
				if ((this._EstadoUsuario != value))
				{
					this._EstadoUsuario = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_BuscarUsuariosRolesResult
	{
		
		private string _CodigoUsuario;
		
		private string _CodigoRol;
		
		private bool _Estado;
		
		private System.DateTime _SegFechaRegistro;
		
		private System.DateTime _SegFechaModifica;
		
		private string _SegUsuarioRegistro;
		
		private string _SegUsuarioModifica;
		
		private string _SegMaquina;
		
		public pa_mnt_BuscarUsuariosRolesResult()
		{
		}
		
		[Column(Storage="_CodigoUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoUsuario
		{
			get
			{
				return this._CodigoUsuario;
			}
			set
			{
				if ((this._CodigoUsuario != value))
				{
					this._CodigoUsuario = value;
				}
			}
		}
		
		[Column(Storage="_CodigoRol", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CodigoRol
		{
			get
			{
				return this._CodigoRol;
			}
			set
			{
				if ((this._CodigoRol != value))
				{
					this._CodigoRol = value;
				}
			}
		}
		
		[Column(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaModifica", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaModifica
		{
			get
			{
				return this._SegFechaModifica;
			}
			set
			{
				if ((this._SegFechaModifica != value))
				{
					this._SegFechaModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioModifica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioModifica
		{
			get
			{
				return this._SegUsuarioModifica;
			}
			set
			{
				if ((this._SegUsuarioModifica != value))
				{
					this._SegUsuarioModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_BuscarRolesOpcionesResult
	{
		
		private string _CodigoRol;
		
		private string _CodigoOpcion;
		
		private bool _Flag_Ver;
		
		private bool _Flag_Eliminar;
		
		private bool _Flag_Editar;
		
		private bool _Flag_Nuevo;
		
		private System.Nullable<System.DateTime> _SegFechaRegistro;
		
		private System.Nullable<System.DateTime> _SegFechaModifica;
		
		private string _SegUsuarioRegistro;
		
		private string _SegUsuarioModifica;
		
		private string _SegMaquina;
		
		public pa_mnt_BuscarRolesOpcionesResult()
		{
		}
		
		[Column(Storage="_CodigoRol", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CodigoRol
		{
			get
			{
				return this._CodigoRol;
			}
			set
			{
				if ((this._CodigoRol != value))
				{
					this._CodigoRol = value;
				}
			}
		}
		
		[Column(Storage="_CodigoOpcion", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CodigoOpcion
		{
			get
			{
				return this._CodigoOpcion;
			}
			set
			{
				if ((this._CodigoOpcion != value))
				{
					this._CodigoOpcion = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Ver", DbType="Bit NOT NULL")]
		public bool Flag_Ver
		{
			get
			{
				return this._Flag_Ver;
			}
			set
			{
				if ((this._Flag_Ver != value))
				{
					this._Flag_Ver = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Eliminar", DbType="Bit NOT NULL")]
		public bool Flag_Eliminar
		{
			get
			{
				return this._Flag_Eliminar;
			}
			set
			{
				if ((this._Flag_Eliminar != value))
				{
					this._Flag_Eliminar = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Editar", DbType="Bit NOT NULL")]
		public bool Flag_Editar
		{
			get
			{
				return this._Flag_Editar;
			}
			set
			{
				if ((this._Flag_Editar != value))
				{
					this._Flag_Editar = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Nuevo", DbType="Bit NOT NULL")]
		public bool Flag_Nuevo
		{
			get
			{
				return this._Flag_Nuevo;
			}
			set
			{
				if ((this._Flag_Nuevo != value))
				{
					this._Flag_Nuevo = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaModifica
		{
			get
			{
				return this._SegFechaModifica;
			}
			set
			{
				if ((this._SegFechaModifica != value))
				{
					this._SegFechaModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioModifica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioModifica
		{
			get
			{
				return this._SegUsuarioModifica;
			}
			set
			{
				if ((this._SegUsuarioModifica != value))
				{
					this._SegUsuarioModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_BuscarOpcionesResult
	{
		
		private string _CodigoOpcion;
		
		private string _CodigoPadre;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _Enlace;
		
		private System.Nullable<char> _FlagMenu;
		
		private char _Estado;
		
		private System.DateTime _SegFechaRegistro;
		
		private System.DateTime _SegFechaModifica;
		
		private string _SegUsuarioRegistro;
		
		private string _SegUsuarioModifica;
		
		private string _SegMaquina;
		
		public pa_mnt_BuscarOpcionesResult()
		{
		}
		
		[Column(Storage="_CodigoOpcion", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CodigoOpcion
		{
			get
			{
				return this._CodigoOpcion;
			}
			set
			{
				if ((this._CodigoOpcion != value))
				{
					this._CodigoOpcion = value;
				}
			}
		}
		
		[Column(Storage="_CodigoPadre", DbType="Char(4)")]
		public string CodigoPadre
		{
			get
			{
				return this._CodigoPadre;
			}
			set
			{
				if ((this._CodigoPadre != value))
				{
					this._CodigoPadre = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[Column(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[Column(Storage="_Enlace", DbType="VarChar(100)")]
		public string Enlace
		{
			get
			{
				return this._Enlace;
			}
			set
			{
				if ((this._Enlace != value))
				{
					this._Enlace = value;
				}
			}
		}
		
		[Column(Storage="_FlagMenu", DbType="Char(1)")]
		public System.Nullable<char> FlagMenu
		{
			get
			{
				return this._FlagMenu;
			}
			set
			{
				if ((this._FlagMenu != value))
				{
					this._FlagMenu = value;
				}
			}
		}
		
		[Column(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaModifica", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaModifica
		{
			get
			{
				return this._SegFechaModifica;
			}
			set
			{
				if ((this._SegFechaModifica != value))
				{
					this._SegFechaModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioModifica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioModifica
		{
			get
			{
				return this._SegUsuarioModifica;
			}
			set
			{
				if ((this._SegUsuarioModifica != value))
				{
					this._SegUsuarioModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
	}
	
	public partial class pa_pro_ListarRolOpcionResult
	{
		
		private string _CodigoRol;
		
		private string _CodigoOpcion;
		
		private string _Enlace;
		
		private string _Nombre;
		
		private string _CodigoPadre;
		
		private System.Nullable<char> _FlagMenu;
		
		private bool _Flag_Ver;
		
		private bool _Flag_Eliminar;
		
		private bool _Flag_Editar;
		
		private bool _Flag_Nuevo;
		
		private string _SegUsuarioRegistro;
		
		private System.Nullable<System.DateTime> _SegFechaRegistro;
		
		private string _SegMaquina;
        private string _Tipo;
		
		public pa_pro_ListarRolOpcionResult()
		{
		}
		
		[Column(Storage="_CodigoRol", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CodigoRol
		{
			get
			{
				return this._CodigoRol;
			}
			set
			{
				if ((this._CodigoRol != value))
				{
					this._CodigoRol = value;
				}
			}
		}
		
		[Column(Storage="_CodigoOpcion", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CodigoOpcion
		{
			get
			{
				return this._CodigoOpcion;
			}
			set
			{
				if ((this._CodigoOpcion != value))
				{
					this._CodigoOpcion = value;
				}
			}
		}
		
		[Column(Storage="_Enlace", DbType="VarChar(100)")]
		public string Enlace
		{
			get
			{
				return this._Enlace;
			}
			set
			{
				if ((this._Enlace != value))
				{
					this._Enlace = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[Column(Storage="_CodigoPadre", DbType="Char(4)")]
		public string CodigoPadre
		{
			get
			{
				return this._CodigoPadre;
			}
			set
			{
				if ((this._CodigoPadre != value))
				{
					this._CodigoPadre = value;
				}
			}
		}
		
		[Column(Storage="_FlagMenu", DbType="Char(1)")]
		public System.Nullable<char> FlagMenu
		{
			get
			{
				return this._FlagMenu;
			}
			set
			{
				if ((this._FlagMenu != value))
				{
					this._FlagMenu = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Ver", DbType="Bit NOT NULL")]
		public bool Flag_Ver
		{
			get
			{
				return this._Flag_Ver;
			}
			set
			{
				if ((this._Flag_Ver != value))
				{
					this._Flag_Ver = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Eliminar", DbType="Bit NOT NULL")]
		public bool Flag_Eliminar
		{
			get
			{
				return this._Flag_Eliminar;
			}
			set
			{
				if ((this._Flag_Eliminar != value))
				{
					this._Flag_Eliminar = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Editar", DbType="Bit NOT NULL")]
		public bool Flag_Editar
		{
			get
			{
				return this._Flag_Editar;
			}
			set
			{
				if ((this._Flag_Editar != value))
				{
					this._Flag_Editar = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Nuevo", DbType="Bit NOT NULL")]
		public bool Flag_Nuevo
		{
			get
			{
				return this._Flag_Nuevo;
			}
			set
			{
				if ((this._Flag_Nuevo != value))
				{
					this._Flag_Nuevo = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}

        [Column(Storage = "_Tipo", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                if ((this._Tipo != value))
                {
                    this._Tipo = value;
                }
            }
        }
	}
	
	public partial class pa_mnt_ListarRolesOpcionesResult
	{
		
		private string _CodigoRol;
		
		private string _CodigoRolNombre;
		
		private string _CodigoOpcion;
		
		private string _CodigoOpcionNombre;
		
		private string _CodigoPadre;
		
		private System.Nullable<char> _FlagMenu;
		
		private bool _Flag_Ver;
		
		private bool _Flag_Eliminar;
		
		private bool _Flag_Editar;
		
		private bool _Flag_Nuevo;
		
		private System.Nullable<System.DateTime> _SegFechaRegistro;
		
		private System.Nullable<System.DateTime> _SegFechaModifica;
		
		private string _SegUsuarioRegistro;
		
		private string _SegUsuarioModifica;
		
		private string _SegMaquina;
		
		public pa_mnt_ListarRolesOpcionesResult()
		{
		}
		
		[Column(Storage="_CodigoRol", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CodigoRol
		{
			get
			{
				return this._CodigoRol;
			}
			set
			{
				if ((this._CodigoRol != value))
				{
					this._CodigoRol = value;
				}
			}
		}
		
		[Column(Storage="_CodigoRolNombre", DbType="VarChar(25)")]
		public string CodigoRolNombre
		{
			get
			{
				return this._CodigoRolNombre;
			}
			set
			{
				if ((this._CodigoRolNombre != value))
				{
					this._CodigoRolNombre = value;
				}
			}
		}
		
		[Column(Storage="_CodigoOpcion", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CodigoOpcion
		{
			get
			{
				return this._CodigoOpcion;
			}
			set
			{
				if ((this._CodigoOpcion != value))
				{
					this._CodigoOpcion = value;
				}
			}
		}
		
		[Column(Storage="_CodigoOpcionNombre", DbType="VarChar(25)")]
		public string CodigoOpcionNombre
		{
			get
			{
				return this._CodigoOpcionNombre;
			}
			set
			{
				if ((this._CodigoOpcionNombre != value))
				{
					this._CodigoOpcionNombre = value;
				}
			}
		}
		
		[Column(Storage="_CodigoPadre", DbType="Char(4)")]
		public string CodigoPadre
		{
			get
			{
				return this._CodigoPadre;
			}
			set
			{
				if ((this._CodigoPadre != value))
				{
					this._CodigoPadre = value;
				}
			}
		}
		
		[Column(Storage="_FlagMenu", DbType="Char(1)")]
		public System.Nullable<char> FlagMenu
		{
			get
			{
				return this._FlagMenu;
			}
			set
			{
				if ((this._FlagMenu != value))
				{
					this._FlagMenu = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Ver", DbType="Bit NOT NULL")]
		public bool Flag_Ver
		{
			get
			{
				return this._Flag_Ver;
			}
			set
			{
				if ((this._Flag_Ver != value))
				{
					this._Flag_Ver = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Eliminar", DbType="Bit NOT NULL")]
		public bool Flag_Eliminar
		{
			get
			{
				return this._Flag_Eliminar;
			}
			set
			{
				if ((this._Flag_Eliminar != value))
				{
					this._Flag_Eliminar = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Editar", DbType="Bit NOT NULL")]
		public bool Flag_Editar
		{
			get
			{
				return this._Flag_Editar;
			}
			set
			{
				if ((this._Flag_Editar != value))
				{
					this._Flag_Editar = value;
				}
			}
		}
		
		[Column(Storage="_Flag_Nuevo", DbType="Bit NOT NULL")]
		public bool Flag_Nuevo
		{
			get
			{
				return this._Flag_Nuevo;
			}
			set
			{
				if ((this._Flag_Nuevo != value))
				{
					this._Flag_Nuevo = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaModifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaModifica
		{
			get
			{
				return this._SegFechaModifica;
			}
			set
			{
				if ((this._SegFechaModifica != value))
				{
					this._SegFechaModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioModifica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioModifica
		{
			get
			{
				return this._SegUsuarioModifica;
			}
			set
			{
				if ((this._SegUsuarioModifica != value))
				{
					this._SegUsuarioModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_BuscarConfigResult
	{
		
		private string _CodConfig;
		
		private string _CodTabla;
		
		private string _CodArgu;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		public pa_mnt_BuscarConfigResult()
		{
		}
		
		[Column(Storage="_CodConfig", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string CodConfig
		{
			get
			{
				return this._CodConfig;
			}
			set
			{
				if ((this._CodConfig != value))
				{
					this._CodConfig = value;
				}
			}
		}
		
		[Column(Storage="_CodTabla", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string CodTabla
		{
			get
			{
				return this._CodTabla;
			}
			set
			{
				if ((this._CodTabla != value))
				{
					this._CodTabla = value;
				}
			}
		}
		
		[Column(Storage="_CodArgu", DbType="VarChar(17)")]
		public string CodArgu
		{
			get
			{
				return this._CodArgu;
			}
			set
			{
				if ((this._CodArgu != value))
				{
					this._CodArgu = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[Column(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_ListarConfigResult
	{
		
		private string _CodConfig;
		
		private string _CodTabla;
		
		private string _CodArgu;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		public pa_mnt_ListarConfigResult()
		{
		}
		
		[Column(Storage="_CodConfig", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string CodConfig
		{
			get
			{
				return this._CodConfig;
			}
			set
			{
				if ((this._CodConfig != value))
				{
					this._CodConfig = value;
				}
			}
		}
		
		[Column(Storage="_CodTabla", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string CodTabla
		{
			get
			{
				return this._CodTabla;
			}
			set
			{
				if ((this._CodTabla != value))
				{
					this._CodTabla = value;
				}
			}
		}
		
		[Column(Storage="_CodArgu", DbType="VarChar(17)")]
		public string CodArgu
		{
			get
			{
				return this._CodArgu;
			}
			set
			{
				if ((this._CodArgu != value))
				{
					this._CodArgu = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[Column(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_BuscarUsuariosResult
	{
		
		private string _LoginUsuario;
		
		private string _PasswordUsuario;
		
		private string _ApellidosUsuario;
		
		private string _NombresUsuario;
		
		private string _CodPersona;
		
		private string _TipoUsuario;
		
		public pa_mnt_BuscarUsuariosResult()
		{
		}
		
		[Column(Storage="_LoginUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginUsuario
		{
			get
			{
				return this._LoginUsuario;
			}
			set
			{
				if ((this._LoginUsuario != value))
				{
					this._LoginUsuario = value;
				}
			}
		}
		
		[Column(Storage="_PasswordUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PasswordUsuario
		{
			get
			{
				return this._PasswordUsuario;
			}
			set
			{
				if ((this._PasswordUsuario != value))
				{
					this._PasswordUsuario = value;
				}
			}
		}
		
		[Column(Storage="_ApellidosUsuario", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string ApellidosUsuario
		{
			get
			{
				return this._ApellidosUsuario;
			}
			set
			{
				if ((this._ApellidosUsuario != value))
				{
					this._ApellidosUsuario = value;
				}
			}
		}
		
		[Column(Storage="_NombresUsuario", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string NombresUsuario
		{
			get
			{
				return this._NombresUsuario;
			}
			set
			{
				if ((this._NombresUsuario != value))
				{
					this._NombresUsuario = value;
				}
			}
		}
		
		[Column(Storage="_CodPersona", DbType="VarChar(20)")]
		public string CodPersona
		{
			get
			{
				return this._CodPersona;
			}
			set
			{
				if ((this._CodPersona != value))
				{
					this._CodPersona = value;
				}
			}
		}
		
		[Column(Storage="_TipoUsuario", DbType="VarChar(5)")]
		public string TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this._TipoUsuario = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_ListarOpcionesResult
	{
		
		private string _CodigoOpcion;
		
		private string _CodigoPadre;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _Enlace;
		
		private System.Nullable<char> _FlagMenu;
		
		private char _Estado;
		
		private System.DateTime _SegFechaRegistro;
		
		private System.DateTime _SegFechaModifica;
		
		private string _SegUsuarioRegistro;
		
		private string _SegUsuarioModifica;
		
		private string _SegMaquina;
		
		public pa_mnt_ListarOpcionesResult()
		{
		}
		
		[Column(Storage="_CodigoOpcion", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CodigoOpcion
		{
			get
			{
				return this._CodigoOpcion;
			}
			set
			{
				if ((this._CodigoOpcion != value))
				{
					this._CodigoOpcion = value;
				}
			}
		}
		
		[Column(Storage="_CodigoPadre", DbType="Char(4)")]
		public string CodigoPadre
		{
			get
			{
				return this._CodigoPadre;
			}
			set
			{
				if ((this._CodigoPadre != value))
				{
					this._CodigoPadre = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[Column(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[Column(Storage="_Enlace", DbType="VarChar(100)")]
		public string Enlace
		{
			get
			{
				return this._Enlace;
			}
			set
			{
				if ((this._Enlace != value))
				{
					this._Enlace = value;
				}
			}
		}
		
		[Column(Storage="_FlagMenu", DbType="Char(1)")]
		public System.Nullable<char> FlagMenu
		{
			get
			{
				return this._FlagMenu;
			}
			set
			{
				if ((this._FlagMenu != value))
				{
					this._FlagMenu = value;
				}
			}
		}
		
		[Column(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaModifica", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaModifica
		{
			get
			{
				return this._SegFechaModifica;
			}
			set
			{
				if ((this._SegFechaModifica != value))
				{
					this._SegFechaModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioModifica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioModifica
		{
			get
			{
				return this._SegUsuarioModifica;
			}
			set
			{
				if ((this._SegUsuarioModifica != value))
				{
					this._SegUsuarioModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
	}
	
	public partial class pa_pro_DetectarLoginResult
	{
		
		private string _LoginUsuario;
		
		private string _NombresUsuario;
		
		private string _ApellidosUsuario;
		
		private bool _EstadoUsuario;
		
		private string _CodigoRol;
		
		private string _CodigoRolNombre;
		
		public pa_pro_DetectarLoginResult()
		{
		}
		
		[Column(Storage="_LoginUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginUsuario
		{
			get
			{
				return this._LoginUsuario;
			}
			set
			{
				if ((this._LoginUsuario != value))
				{
					this._LoginUsuario = value;
				}
			}
		}
		
		[Column(Storage="_NombresUsuario", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string NombresUsuario
		{
			get
			{
				return this._NombresUsuario;
			}
			set
			{
				if ((this._NombresUsuario != value))
				{
					this._NombresUsuario = value;
				}
			}
		}
		
		[Column(Storage="_ApellidosUsuario", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string ApellidosUsuario
		{
			get
			{
				return this._ApellidosUsuario;
			}
			set
			{
				if ((this._ApellidosUsuario != value))
				{
					this._ApellidosUsuario = value;
				}
			}
		}
		
		[Column(Storage="_EstadoUsuario", DbType="Bit NOT NULL")]
		public bool EstadoUsuario
		{
			get
			{
				return this._EstadoUsuario;
			}
			set
			{
				if ((this._EstadoUsuario != value))
				{
					this._EstadoUsuario = value;
				}
			}
		}
		
		[Column(Storage="_CodigoRol", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CodigoRol
		{
			get
			{
				return this._CodigoRol;
			}
			set
			{
				if ((this._CodigoRol != value))
				{
					this._CodigoRol = value;
				}
			}
		}
		
		[Column(Storage="_CodigoRolNombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CodigoRolNombre
		{
			get
			{
				return this._CodigoRolNombre;
			}
			set
			{
				if ((this._CodigoRolNombre != value))
				{
					this._CodigoRolNombre = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_ListarRolesResult
	{
		
		private string _CodigoRol;
		
		private string _NombreRol;
		
		private string _DescripcionRol;
		
		private char _Estado;
		
		private System.DateTime _SegFechaRegistro;
		
		private System.DateTime _SegFechaModifica;
		
		private string _SegUsuarioRegistro;
		
		private string _SegUsuarioModifica;
		
		private string _SegMaquina;
		
		private bool _TodosLosCentros;
		
		public pa_mnt_ListarRolesResult()
		{
		}
		
		[Column(Storage="_CodigoRol", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CodigoRol
		{
			get
			{
				return this._CodigoRol;
			}
			set
			{
				if ((this._CodigoRol != value))
				{
					this._CodigoRol = value;
				}
			}
		}
		
		[Column(Storage="_NombreRol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string NombreRol
		{
			get
			{
				return this._NombreRol;
			}
			set
			{
				if ((this._NombreRol != value))
				{
					this._NombreRol = value;
				}
			}
		}
		
		[Column(Storage="_DescripcionRol", DbType="VarChar(50)")]
		public string DescripcionRol
		{
			get
			{
				return this._DescripcionRol;
			}
			set
			{
				if ((this._DescripcionRol != value))
				{
					this._DescripcionRol = value;
				}
			}
		}
		
		[Column(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaModifica", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaModifica
		{
			get
			{
				return this._SegFechaModifica;
			}
			set
			{
				if ((this._SegFechaModifica != value))
				{
					this._SegFechaModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioModifica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioModifica
		{
			get
			{
				return this._SegUsuarioModifica;
			}
			set
			{
				if ((this._SegUsuarioModifica != value))
				{
					this._SegUsuarioModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
		
		[Column(Storage="_TodosLosCentros", DbType="Bit NOT NULL")]
		public bool TodosLosCentros
		{
			get
			{
				return this._TodosLosCentros;
			}
			set
			{
				if ((this._TodosLosCentros != value))
				{
					this._TodosLosCentros = value;
				}
			}
		}
	}
	
	public partial class pa_mnt_BuscarRolesResult
	{
		
		private string _CodigoRol;
		
		private string _NombreRol;
		
		private string _DescripcionRol;
		
		private char _Estado;
		
		private System.DateTime _SegFechaRegistro;
		
		private System.DateTime _SegFechaModifica;
		
		private string _SegUsuarioRegistro;
		
		private string _SegUsuarioModifica;
		
		private string _SegMaquina;
		
		private bool _TodosLosCentros;
		
		public pa_mnt_BuscarRolesResult()
		{
		}
		
		[Column(Storage="_CodigoRol", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CodigoRol
		{
			get
			{
				return this._CodigoRol;
			}
			set
			{
				if ((this._CodigoRol != value))
				{
					this._CodigoRol = value;
				}
			}
		}
		
		[Column(Storage="_NombreRol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string NombreRol
		{
			get
			{
				return this._NombreRol;
			}
			set
			{
				if ((this._NombreRol != value))
				{
					this._NombreRol = value;
				}
			}
		}
		
		[Column(Storage="_DescripcionRol", DbType="VarChar(50)")]
		public string DescripcionRol
		{
			get
			{
				return this._DescripcionRol;
			}
			set
			{
				if ((this._DescripcionRol != value))
				{
					this._DescripcionRol = value;
				}
			}
		}
		
		[Column(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaRegistro
		{
			get
			{
				return this._SegFechaRegistro;
			}
			set
			{
				if ((this._SegFechaRegistro != value))
				{
					this._SegFechaRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegFechaModifica", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaModifica
		{
			get
			{
				return this._SegFechaModifica;
			}
			set
			{
				if ((this._SegFechaModifica != value))
				{
					this._SegFechaModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioRegistro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioRegistro
		{
			get
			{
				return this._SegUsuarioRegistro;
			}
			set
			{
				if ((this._SegUsuarioRegistro != value))
				{
					this._SegUsuarioRegistro = value;
				}
			}
		}
		
		[Column(Storage="_SegUsuarioModifica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SegUsuarioModifica
		{
			get
			{
				return this._SegUsuarioModifica;
			}
			set
			{
				if ((this._SegUsuarioModifica != value))
				{
					this._SegUsuarioModifica = value;
				}
			}
		}
		
		[Column(Storage="_SegMaquina", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
		
		[Column(Storage="_TodosLosCentros", DbType="Bit NOT NULL")]
		public bool TodosLosCentros
		{
			get
			{
				return this._TodosLosCentros;
			}
			set
			{
				if ((this._TodosLosCentros != value))
				{
					this._TodosLosCentros = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
